"""
Python broker adapter contract.

This file is the Python counterpart to frontend/lib/brokers/adapter.ts.
The TypeScript file is the CANONICAL contract — this file mirrors it in
Python types so the backend can enforce the same interface at runtime.

SYNC REQUIREMENT: Any change to method signatures or DTO shapes requires
updating BOTH this file AND frontend/lib/brokers/adapter.ts, and a reviewer
pass on the diff. Open a single PR that modifies both files together; the PR
description must note the sync. See docs/decisions/004-adapter-language-split.md.

Architecture: frontend/lib/brokers/adapter.ts  →  types/contract only (TS)
              backend/app/brokers/<broker>/     →  implementations (Python)
              backend/app/brokers/adapter.py   →  this file — Python ABC
"""
from __future__ import annotations

import abc
from collections.abc import Callable
from datetime import datetime
from typing import Literal, NewType, Optional

from pydantic import BaseModel

# ─── Identity ────────────────────────────────────────────────────────────────

BrokerId = Literal["zerodha", "upstox", "dhan"]

# ─── Branded types ────────────────────────────────────────────────────────────
# Python NewType is erased at runtime (unlike TS brands) but signals intent
# to readers and type-checkers. Treat these as opaque — never construct one
# from an arbitrary string in app code; only adapters produce them.

IdempotencyKey = NewType("IdempotencyKey", str)
BrokerOrderId = NewType("BrokerOrderId", str)

# ─── Credentials ─────────────────────────────────────────────────────────────


class BrokerCredentials(BaseModel):
    """
    Opaque credential bundle. App code must not read individual fields —
    pass the whole object back to the adapter. Mirrors BrokerCredentials in TS.
    """

    broker_id: BrokerId
    access_token: str
    expires_at: datetime
    refresh_token: Optional[str] = None

    model_config = {"frozen": True}


# ─── Profile & Account ────────────────────────────────────────────────────────


class BrokerProfile(BaseModel):
    broker_id: BrokerId
    user_id: str
    display_name: str
    email: str

    model_config = {"frozen": True}


class Position(BaseModel):
    symbol: str
    exchange: Literal["NSE", "BSE"]
    quantity: int  # positive = long, negative = short
    average_price: float
    pnl: float
    day_pnl: float

    model_config = {"frozen": True}


class Holding(BaseModel):
    symbol: str
    exchange: Literal["NSE", "BSE"]
    quantity: int
    average_price: float
    current_value: float
    pnl: float

    model_config = {"frozen": True}


# ─── Orders ───────────────────────────────────────────────────────────────────

OrderSide = Literal["BUY", "SELL"]
ProductType = Literal["CNC", "MIS", "NRML"]
OrderValidity = Literal["DAY", "IOC"]
CanonicalOrderType = Literal["MARKET", "LIMIT", "SL", "SL_MARKET"]


class ZerodhaExtensions(BaseModel):
    variety: Optional[Literal["regular", "co", "bo", "amo", "iceberg", "auction"]] = None
    trigger_price: Optional[float] = None
    squareoff_absolute: Optional[float] = None
    stoploss_absolute: Optional[float] = None
    trailing_stoploss: Optional[float] = None
    iceberg_legs: Optional[int] = None
    iceberg_quantity: Optional[int] = None


class UpstoxExtensions(BaseModel):
    sl_order_type: Optional[Literal["SL", "SL-M"]] = None
    amo_session: Optional[Literal["PRE_OPEN", "OPEN", "OPEN_30", "OPEN_60"]] = None


class DhanExtensions(BaseModel):
    after_market_order: Optional[bool] = None
    sl_order_type: Optional[Literal["SL", "SL-M"]] = None


class OrderExtensions(BaseModel):
    """
    Broker-specific extension fields. Only the extension matching the target
    broker should be set. Each adapter validates its own key at runtime.

    TypeScript enforces this at compile time via Pick<OrderExtensions, B>.
    Python cannot replicate compile-time narrowing — runtime enforcement is
    in each adapter's place_order implementation.
    """

    zerodha: Optional[ZerodhaExtensions] = None
    upstox: Optional[UpstoxExtensions] = None
    dhan: Optional[DhanExtensions] = None


class OrderRequest(BaseModel):
    """
    Mirrors OrderRequest<B> from TS. idempotency_key must be a UUID v4
    (max 36 chars) generated by the caller before each genuine new order.
    See TypeScript source for full idempotency deduplication contract.
    """

    idempotency_key: IdempotencyKey
    symbol: str
    exchange: Literal["NSE", "BSE"]
    side: OrderSide
    quantity: int
    order_type: CanonicalOrderType
    limit_price: Optional[float] = None
    trigger_price: Optional[float] = None
    product: ProductType
    validity: OrderValidity
    extensions: Optional[OrderExtensions] = None


class OrderPatch(BaseModel):
    quantity: Optional[int] = None
    limit_price: Optional[float] = None
    trigger_price: Optional[float] = None
    validity: Optional[OrderValidity] = None


# ─── Order Status ─────────────────────────────────────────────────────────────

OrderStatus = Literal["PENDING", "OPEN", "PARTIAL", "COMPLETE", "CANCELLED", "REJECTED"]


class Fill(BaseModel):
    """
    fill_quantity is THIS event's quantity only — not cumulative.
    Use trade_id to deduplicate on reconnect.
    """

    trade_id: str
    broker_order_id: BrokerOrderId
    symbol: str
    side: OrderSide
    fill_quantity: int
    fill_price: float
    filled_at: datetime

    model_config = {"frozen": True}


class Order(BaseModel):
    """
    id is our internal IdempotencyKey — NOT the broker's order ID.
    broker_order_id is the broker's assigned ID; use it for modify/cancel/get.
    filled_quantity is the cumulative total across all fills.
    """

    id: IdempotencyKey
    broker_order_id: BrokerOrderId
    symbol: str
    exchange: Literal["NSE", "BSE"]
    side: OrderSide
    order_type: CanonicalOrderType
    product: ProductType
    status: OrderStatus
    quantity: int
    filled_quantity: int
    average_price: float
    fills: list[Fill]
    child_broker_order_ids: list[BrokerOrderId]
    limit_price: Optional[float] = None
    trigger_price: Optional[float] = None
    placed_at: datetime
    updated_at: datetime
    rejection_reason: Optional[str] = None

    model_config = {"frozen": True}


class OrderResult(BaseModel):
    order: Order
    from_cache: bool  # True when idempotency key matched an existing row

    model_config = {"frozen": True}


class ModifyResult(BaseModel):
    order: Order  # post-modify/cancel snapshot

    model_config = {"frozen": True}


# ─── Error model ─────────────────────────────────────────────────────────────

BrokerErrorKind = Literal[
    "INVALID_REQUEST",
    "AUTH_EXPIRED",
    "BROKER_REJECTED",
    "TIMEOUT",
    "RATE_LIMITED",
    "NETWORK",
    "UNKNOWN",
]


class BrokerError(Exception):
    """
    Raised by all adapter methods on failure. Never let raw broker SDK errors
    escape an adapter — always catch and wrap in BrokerError.

    Kind semantics: see BrokerErrorKind docstring in adapter.ts for the full
    contract. Key points:
      TIMEOUT / NETWORK → possibly_executed=True; check listOrders before retry
      RATE_LIMITED      → retryable=True after retry_after_ms
      BROKER_REJECTED   → not retryable, not possibly_executed
    """

    def __init__(
        self,
        *,
        kind: BrokerErrorKind,
        broker_id: BrokerId,
        message: str,
        retryable: bool,
        possibly_executed: bool = False,
        cause: Optional[BaseException] = None,
        broker_code: Optional[str] = None,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        self.kind = kind
        self.broker_id = broker_id
        self.retryable = retryable
        self.possibly_executed = possibly_executed
        self.cause = cause
        self.broker_code = broker_code
        self.retry_after_ms = retry_after_ms

    def __repr__(self) -> str:
        return (
            f"BrokerError(kind={self.kind!r}, broker_id={self.broker_id!r}, "
            f"message={str(self)!r}, retryable={self.retryable})"
        )


# ─── Streaming ────────────────────────────────────────────────────────────────

FillCallback = Callable[[Fill], None]
Unsubscribe = Callable[[], None]


# ─── The contract ─────────────────────────────────────────────────────────────


class BrokerAdapter(abc.ABC):
    """
    Abstract base class every broker adapter must subclass.

    Mirrors BrokerAdapter<B> from frontend/lib/brokers/adapter.ts.
    Keep both files in sync — see module docstring for the sync contract.

    Naming: TypeScript camelCase methods map to Python snake_case here.
    Semantics are identical; only surface syntax differs.
    """

    @property
    @abc.abstractmethod
    def id(self) -> BrokerId: ...

    @property
    @abc.abstractmethod
    def supports_streaming_fills(self) -> bool: ...

    # Auth ────────────────────────────────────────────────────────────────────

    @abc.abstractmethod
    def get_auth_url(self, state: str) -> str:
        """Return the broker OAuth login URL. state is an opaque CSRF token."""

    @abc.abstractmethod
    async def exchange_code(self, code: str) -> BrokerCredentials:
        """Exchange an OAuth request_token/code for BrokerCredentials."""

    @abc.abstractmethod
    async def refresh(self, creds: BrokerCredentials) -> BrokerCredentials:
        """
        Refresh via refresh_token. Raises BrokerError(kind='AUTH_EXPIRED')
        for brokers that don't support refresh (e.g. Zerodha daily login).
        Caller must then redirect to get_auth_url().
        """

    # Account ─────────────────────────────────────────────────────────────────

    @abc.abstractmethod
    async def get_profile(self, creds: BrokerCredentials) -> BrokerProfile: ...

    @abc.abstractmethod
    async def get_positions(self, creds: BrokerCredentials) -> list[Position]: ...

    @abc.abstractmethod
    async def get_holdings(self, creds: BrokerCredentials) -> list[Holding]: ...

    # Orders ──────────────────────────────────────────────────────────────────

    @abc.abstractmethod
    async def place_order(
        self, creds: BrokerCredentials, order: OrderRequest
    ) -> OrderResult:
        """
        Place an order. MUST check order_idempotency table before calling broker.
        If order.idempotency_key matches an existing row, return cached result
        with from_cache=True — do NOT call the broker again.
        """

    @abc.abstractmethod
    async def modify_order(
        self,
        creds: BrokerCredentials,
        broker_order_id: BrokerOrderId,
        patch: OrderPatch,
    ) -> ModifyResult: ...

    @abc.abstractmethod
    async def cancel_order(
        self,
        creds: BrokerCredentials,
        broker_order_id: BrokerOrderId,
    ) -> ModifyResult: ...

    @abc.abstractmethod
    async def get_order(
        self,
        creds: BrokerCredentials,
        broker_order_id: BrokerOrderId,
    ) -> Order:
        """
        MUST return complete fill history. If the broker needs a separate
        fills endpoint (e.g. Kite /orders/{id}/trades), call it and merge.
        Returning fills=[] when fills have occurred is a contract violation.
        """

    @abc.abstractmethod
    async def list_orders(self, creds: BrokerCredentials) -> list[Order]: ...

    @abc.abstractmethod
    def subscribe_fills(
        self, creds: BrokerCredentials, on_fill: FillCallback
    ) -> Unsubscribe:
        """
        Subscribe to real-time fill events. MUST always return an Unsubscribe
        callable. If supports_streaming_fills is False, return a no-op lambda
        so caller cleanup code is identical in both cases.
        """
