/**
 * BrokerAdapter — canonical contract for all broker integrations.
 *
 * ARCHITECTURE: This file is TYPES ONLY. Do not add implementation code here.
 * All real broker logic lives in backend/app/brokers/<broker>/ (Python/FastAPI).
 * The frontend calls the backend over HTTP — it never calls broker APIs directly.
 * broker API keys must never reach the browser.
 *
 * SYNC: The Python counterpart is backend/app/brokers/adapter.py. Any change
 * to method signatures or DTO shapes must update both files in the same PR.
 * See docs/decisions/004-adapter-language-split.md for full rationale.
 *
 * Import ONLY from this file in frontend code. Never import from
 * lib/brokers/<broker>/ directly.
 */

// ─── Identity ────────────────────────────────────────────────────────────────

export type BrokerId = "zerodha" | "upstox" | "dhan";

// ─── Branded types ────────────────────────────────────────────────────────────

/**
 * Our internal idempotency key, generated by the caller before placeOrder.
 * Must be a UUID v4 (max 36 chars). Used as the primary key in the
 * `order_idempotency` DB table — see migration 025_order_idempotency.sql.
 */
export type IdempotencyKey = string & { readonly __brand: "IdempotencyKey" };

/**
 * The broker's own order ID, assigned by the broker after a successful
 * placeOrder call. Completely different from our IdempotencyKey.
 * modifyOrder, cancelOrder, and getOrder all take this — never our key.
 */
export type BrokerOrderId = string & { readonly __brand: "BrokerOrderId" };

export function toIdempotencyKey(s: string): IdempotencyKey {
  return s as IdempotencyKey;
}

export function toBrokerOrderId(s: string): BrokerOrderId {
  return s as BrokerOrderId;
}

// ─── Credentials ─────────────────────────────────────────────────────────────

/**
 * Opaque credential bundle returned by exchangeCode / refresh.
 * App code must not read individual fields — pass the whole object back to the
 * adapter. The adapter implementation knows which fields it needs.
 */
export interface BrokerCredentials {
  readonly brokerId: BrokerId;
  readonly accessToken: string;
  readonly expiresAt: Date;
  /** Refresh token if the broker supports it; undefined if not (e.g. Zerodha daily login). */
  readonly refreshToken?: string;
}

// ─── Profile & Positions ─────────────────────────────────────────────────────

export interface BrokerProfile {
  readonly brokerId: BrokerId;
  readonly userId: string;
  readonly displayName: string;
  readonly email: string;
}

export interface Position {
  readonly symbol: string;
  readonly exchange: "NSE" | "BSE";
  /**
   * Positive = long, negative = short.
   * E.g. a short of 50 shares is represented as -50.
   */
  readonly quantity: number;
  readonly averagePrice: number;
  readonly pnl: number;
  readonly dayPnl: number;
}

export interface Holding {
  readonly symbol: string;
  readonly exchange: "NSE" | "BSE";
  readonly quantity: number;
  readonly averagePrice: number;
  readonly currentValue: number;
  readonly pnl: number;
}

// ─── Orders ───────────────────────────────────────────────────────────────────

export type OrderSide = "BUY" | "SELL";
export type ProductType = "CNC" | "MIS" | "NRML";
export type OrderValidity = "DAY" | "IOC";

/**
 * Canonical order types alphavyuh exposes to the app layer.
 * Broker-specific order types (CO, BO, AMO, etc.) are expressed via
 * the `extensions` field on `OrderRequest` so they never leak into app-layer code.
 */
export type CanonicalOrderType = "MARKET" | "LIMIT" | "SL" | "SL_MARKET";

/**
 * Broker-specific extensions, keyed by BrokerId.
 *
 * COMPILE-TIME SAFETY: OrderRequest<B> only exposes extensions[B]. An order
 * constructed for a Zerodha adapter cannot accidentally contain Upstox
 * extensions — the type system won't allow it.
 *
 * App-layer code that constructs an OrderRequest<"zerodha"> may only set
 * `extensions.zerodha`. The adapter reads only its own key and the TypeScript
 * compiler enforces this at the call site.
 */
export type OrderExtensions = {
  readonly zerodha?: {
    readonly variety?: "regular" | "co" | "bo" | "amo" | "iceberg" | "auction";
    readonly triggerPrice?: number;
    /**
     * For BO only. Value is an absolute tick offset (not a percentage).
     * E.g. squareoffAbsolute: 10 means take profit 10 points above entry.
     */
    readonly squareoffAbsolute?: number;
    /**
     * For BO only. Value is an absolute tick offset (not a percentage).
     * E.g. stoplossAbsolute: 5 means stop loss 5 points below entry.
     */
    readonly stoplossAbsolute?: number;
    readonly trailingStoploss?: number;
    readonly icebergLegs?: number;
    readonly icebergQuantity?: number;
  };
  readonly upstox?: {
    readonly instrumentToken?: string;
    readonly slOrderType?: "SL" | "SL-M";
    readonly amoSession?: "PRE_OPEN" | "OPEN" | "OPEN_30" | "OPEN_60";
  };
  readonly dhan?: {
    readonly afterMarketOrder?: boolean;
    readonly slOrderType?: "SL" | "SL-M";
  };
};

/**
 * Narrows OrderExtensions to only the key for broker B.
 * An OrderRequest<"zerodha"> can only set extensions.zerodha — the compiler
 * rejects any attempt to set extensions.upstox or extensions.dhan.
 */
export type BrokerExtensions<B extends BrokerId> = Pick<OrderExtensions, B>;

export interface OrderRequest<B extends BrokerId = BrokerId> {
  /**
   * Client-generated IdempotencyKey (UUID v4, max 36 chars).
   *
   * Deduplication contract:
   * - The adapter checks the `order_idempotency` DB table BEFORE calling the
   *   broker. If a row with this key already exists, it returns the cached
   *   OrderResult (fromCache: true) without making any broker API call.
   * - The check + insert is a DB-level `INSERT ... ON CONFLICT DO NOTHING`.
   *   This is the only safe mechanism against concurrent duplicate submissions
   *   (e.g. user double-tap). An in-memory cache is NOT sufficient — it does
   *   not survive server restarts and is not shared across Next.js lambda
   *   instances.
   * - Fresh key = a genuinely new order the caller intends to place.
   *   Same key = an idempotent retry of a previous attempt ("did that order
   *   actually go through?"). The caller chooses based on intent — both are
   *   valid uses. Never reuse a key for a different order.
   */
  readonly idempotencyKey: IdempotencyKey;
  readonly symbol: string;
  readonly exchange: "NSE" | "BSE";
  readonly side: OrderSide;
  readonly quantity: number;
  readonly orderType: CanonicalOrderType;
  readonly limitPrice?: number;
  readonly triggerPrice?: number;
  readonly product: ProductType;
  readonly validity: OrderValidity;
  /**
   * Broker-specific extensions. Only the extension key for broker B is allowed.
   * See OrderExtensions for per-broker fields.
   *
   * CO/BO limitation: these order types produce multiple legs at the broker.
   * The adapter returns the parent order only. Child leg IDs are available
   * via Order.childBrokerOrderIds but cannot be managed independently through
   * this interface. See docs/broker-adapter.md for CO/BO lifecycle details.
   */
  readonly extensions?: BrokerExtensions<B>;
}

export interface OrderPatch {
  readonly quantity?: number;
  readonly limitPrice?: number;
  readonly triggerPrice?: number;
  readonly validity?: OrderValidity;
}

// ─── Order Status ─────────────────────────────────────────────────────────────

/**
 * Canonical status set. Broker-specific statuses (e.g. Zerodha's "TRIGGER PENDING")
 * are mapped to these by the adapter before surfacing to the app.
 */
export type OrderStatus =
  | "PENDING"    // placed, not yet processed by exchange
  | "OPEN"       // live on exchange, awaiting fill
  | "PARTIAL"    // partially filled; filledQuantity < quantity
  | "COMPLETE"   // fully filled; filledQuantity === quantity
  | "CANCELLED"  // cancelled by user or exchange; check filledQuantity for any partial fills before cancel
  | "REJECTED";  // rejected; see rejectionReason

export interface Fill {
  /**
   * Exchange-assigned unique trade ID for this fill event.
   * Use this to deduplicate fills on reconnect — the same fill may be
   * re-delivered by the broker's streaming feed after a reconnect.
   */
  readonly tradeId: string;
  /**
   * The broker's order ID for this fill. Typed as BrokerOrderId because broker
   * streaming feeds only know the broker's own order identifier — they have no
   * knowledge of our internal IdempotencyKey. Callers that need to map fills
   * back to an OrderRequest should join on Order.brokerOrderId, which they
   * already hold from the placeOrder result.
   */
  readonly brokerOrderId: BrokerOrderId;
  readonly symbol: string;
  readonly side: OrderSide;
  /**
   * Quantity filled in THIS specific fill event only (not cumulative).
   * Accumulate across fill events to get total filledQuantity.
   * Consistent with Order.filledQuantity which is the cumulative total.
   */
  readonly fillQuantity: number;
  readonly fillPrice: number;
  readonly filledAt: Date;
}

export interface Order {
  /**
   * Our internal key — equals the IdempotencyKey from the original OrderRequest.
   * This is NOT the broker's order ID. Never pass this to broker API calls.
   */
  readonly id: IdempotencyKey;
  /**
   * The broker's own order identifier, assigned after a successful placement.
   * Use this for modifyOrder, cancelOrder, and getOrder.
   */
  readonly brokerOrderId: BrokerOrderId;
  readonly symbol: string;
  readonly exchange: "NSE" | "BSE";
  readonly side: OrderSide;
  readonly orderType: CanonicalOrderType;
  readonly product: ProductType;
  readonly status: OrderStatus;
  readonly quantity: number;
  /**
   * Cumulative quantity filled across ALL fill events to date.
   * Always monotonically increasing. Zero until the first partial fill.
   * For a complete order: filledQuantity === quantity.
   * For a cancelled order: filledQuantity reflects any fills before cancellation.
   *
   * Polling (getOrder): returns the running total as of the API call.
   * Streaming (subscribeFills): each Fill.fillQuantity is the delta for that
   *   event; accumulate them to reproduce filledQuantity.
   * Both paths are consistent — getOrder().filledQuantity equals the sum of
   * all Fill.fillQuantity values received so far.
   */
  readonly filledQuantity: number;
  /**
   * Volume-weighted average fill price across all fills. Zero if unfilled.
   * Recomputed by the adapter on each getOrder call and fill event.
   */
  readonly averagePrice: number;
  /**
   * Complete fill history for this order.
   *
   * getOrder() MUST return the full history to date. If the broker requires a
   * separate API call to retrieve fills (e.g. Zerodha /orders/{id}/trades),
   * the adapter MUST make that call and merge the results before returning.
   * An adapter MUST NOT return fills: [] when fills have occurred.
   *
   * subscribeFills delivers individual Fill events in real time.
   * The Order snapshot returned alongside each event includes fills up to
   * and including the current event.
   */
  readonly fills: Fill[];
  /**
   * IDs of child orders created by the broker for multi-leg types (CO, BO).
   * Empty for regular orders. The caller can use these to check child order
   * status via getOrder, but cannot modify or cancel child legs independently
   * through this interface.
   */
  readonly childBrokerOrderIds: BrokerOrderId[];
  readonly limitPrice?: number;
  readonly triggerPrice?: number;
  readonly placedAt: Date;
  readonly updatedAt: Date;
  /**
   * Set when status === "REJECTED". Human-readable; scrubbed of sensitive data.
   * Examples: "Insufficient margin", "Market is closed", "Invalid symbol".
   * The adapter maps raw broker error codes to plain English — never expose
   * broker internal codes (e.g. "ISEC0098") in this field.
   */
  readonly rejectionReason?: string;
}

// ─── OrderResult & ModifyResult ───────────────────────────────────────────────

/**
 * Returned by placeOrder.
 *
 * Exchange-level rejection note: if the broker accepts the order (assigns a
 * brokerOrderId) but the exchange subsequently rejects it, the adapter MUST
 * return an OrderResult with order.status === "REJECTED" and
 * order.rejectionReason set. Do NOT throw BrokerError in this case — the order
 * exists in the broker's system and has a brokerOrderId that the caller needs.
 * Only throw BrokerError if the broker itself refuses to create the order.
 *
 * fromCache: true when the idempotencyKey matched a row in the
 * `order_idempotency` DB table — the broker was NOT contacted again.
 */
export interface OrderResult {
  readonly order: Order;
  readonly fromCache: boolean;
}

/**
 * Returned by modifyOrder and cancelOrder.
 * The Order snapshot reflects the state immediately after the modify/cancel.
 * For cancelOrder: check order.filledQuantity and order.status to determine
 * how much was filled before the cancel took effect.
 * No fromCache field — modify and cancel are not idempotent by design.
 */
export interface ModifyResult {
  readonly order: Order;
}

// ─── Error model ─────────────────────────────────────────────────────────────

/**
 * Thrown by all adapter methods on failure. Never throw raw broker SDK errors
 * out of an adapter — always wrap in BrokerError.
 *
 * Kind semantics:
 *
 *   INVALID_REQUEST  — the OrderRequest is malformed (e.g. LIMIT order without
 *                      limitPrice, quantity: 0). The broker was NOT contacted.
 *                      retryable: false. Fix the request before retrying.
 *
 *   AUTH_EXPIRED     — access token has expired. retryable: false.
 *                      Recovery: call refresh(creds). If the broker does not
 *                      support refresh (e.g. Zerodha), redirect to getAuthUrl.
 *
 *   BROKER_REJECTED  — the broker explicitly rejected the request before or
 *                      during order creation (e.g. insufficient margin, invalid
 *                      symbol). retryable: false — retrying will produce the
 *                      same result. possiblyExecuted: always false.
 *
 *   TIMEOUT          — no response was received within the adapter's deadline.
 *                      retryable: false. possiblyExecuted: true.
 *                      The request MAY have reached the broker. Call listOrders
 *                      to check before placing a new order — retrying risks a
 *                      duplicate even though the transport is available again.
 *
 *   RATE_LIMITED     — broker returned a rate-limit response (429 or equivalent).
 *                      retryable: true after retryAfterMs (if provided).
 *                      possiblyExecuted: false — rate-limit means the request
 *                      was rejected before it reached order processing.
 *
 *   NETWORK          — network failure before any response was received.
 *                      retryable: false. possiblyExecuted: true.
 *                      Same guidance as TIMEOUT.
 *
 *   UNKNOWN          — anything not covered above. Check cause for the original.
 *                      possiblyExecuted: true (conservative — assume the worst).
 */
export type BrokerErrorKind =
  | "INVALID_REQUEST"
  | "AUTH_EXPIRED"
  | "BROKER_REJECTED"
  | "TIMEOUT"
  | "RATE_LIMITED"
  | "NETWORK"
  | "UNKNOWN";

export class BrokerError extends Error {
  readonly kind: BrokerErrorKind;
  readonly brokerId: BrokerId;
  /**
   * Whether retrying with the same request is safe and likely to succeed.
   * Authoritative values are defined per kind in the BrokerErrorKind JSDoc above.
   * For order placement: always check possiblyExecuted before retrying —
   * retryable: true does not guarantee the original order was not received.
   */
  readonly retryable: boolean;
  /**
   * Whether the original request may have been received and processed by the
   * broker before the error occurred. Authoritative values per kind:
   *   INVALID_REQUEST  → false (broker was never contacted)
   *   AUTH_EXPIRED     → false
   *   BROKER_REJECTED  → false
   *   TIMEOUT          → true  (request was in-flight)
   *   RATE_LIMITED     → false (rejected before order processing)
   *   NETWORK          → true  (request may have reached the broker)
   *   UNKNOWN          → true  (conservative — assume the worst)
   * When true: call listOrders before placing a new order.
   */
  readonly possiblyExecuted: boolean;
  /** The original broker SDK error. For internal logging only — never expose to users. */
  readonly cause?: unknown;
  /** Broker's raw error code (e.g. "ISEC0098"). For internal logging only. */
  readonly brokerCode?: string;
  /**
   * For RATE_LIMITED: milliseconds to wait before the next retry, parsed from
   * the broker's Retry-After header. Undefined if the broker did not provide it.
   */
  readonly retryAfterMs?: number;

  constructor(opts: {
    kind: BrokerErrorKind;
    brokerId: BrokerId;
    message: string;
    retryable: boolean;
    possiblyExecuted?: boolean;
    cause?: unknown;
    brokerCode?: string;
    retryAfterMs?: number;
  }) {
    super(opts.message);
    this.name = "BrokerError";
    this.kind = opts.kind;
    this.brokerId = opts.brokerId;
    this.retryable = opts.retryable;
    this.possiblyExecuted = opts.possiblyExecuted ?? false;
    this.cause = opts.cause;
    this.brokerCode = opts.brokerCode;
    this.retryAfterMs = opts.retryAfterMs;
  }
}

// ─── Streaming ────────────────────────────────────────────────────────────────

export type Unsubscribe = () => void;

// ─── The contract ─────────────────────────────────────────────────────────────

/**
 * BrokerAdapter<B> is generic on BrokerId so that OrderRequest<B> only allows
 * extensions for broker B. This is enforced at compile time — a caller who
 * holds a BrokerAdapter<"zerodha"> cannot accidentally pass Upstox extensions
 * and have them silently ignored.
 */
export interface BrokerAdapter<B extends BrokerId = BrokerId> {
  readonly id: B;

  /**
   * True if this broker supports real-time fill streaming via subscribeFills.
   * If false, subscribeFills returns a no-op Unsubscribe immediately and the
   * caller should fall back to polling getOrder.
   */
  readonly supportsStreamingFills: boolean;

  // Auth
  getAuthUrl(state: string): string;
  exchangeCode(code: string): Promise<BrokerCredentials>;
  /**
   * Refresh credentials using refreshToken.
   * Throws BrokerError(AUTH_EXPIRED, retryable: false) if the broker does not
   * support refresh tokens (e.g. Zerodha). Caller must redirect to getAuthUrl.
   */
  refresh(creds: BrokerCredentials): Promise<BrokerCredentials>;

  // Account
  getProfile(creds: BrokerCredentials): Promise<BrokerProfile>;
  getPositions(creds: BrokerCredentials): Promise<Position[]>;
  getHoldings(creds: BrokerCredentials): Promise<Holding[]>;

  // Orders
  /**
   * Place an order.
   * userId is required because idempotency is scoped to (user_id, idempotency_key)
   * in Supabase before any broker request is sent.
   *
   * Idempotency (mandatory):
   * Before calling the broker, the adapter checks the `order_idempotency` DB
   * table for a row matching order.idempotencyKey using:
   *   INSERT INTO order_idempotency (user_id, idempotency_key, broker_id, result)
   *   VALUES ($user_id, $key, $broker_id, NULL)
   *   ON CONFLICT (user_id, idempotency_key) DO NOTHING
   * If the INSERT was a no-op (conflict), the existing result is returned with
   * fromCache: true — the broker is NOT called again. This is safe against
   * concurrent duplicate submissions (double-tap, retry storms).
   *
   * Rejection semantics:
   * If the broker accepts the order (assigns a brokerOrderId) but the exchange
   * rejects it, return OrderResult with order.status === "REJECTED".
   * Do NOT throw — the brokerOrderId must be surfaced to the caller.
   * Only throw BrokerError if the broker refuses to create the order at all.
   *
   * Throws BrokerError on all failure modes. Never throws a raw SDK error.
   */
  placeOrder(
    userId: string,
    creds: BrokerCredentials,
    order: OrderRequest<B>
  ): Promise<OrderResult>;

  /**
   * Modify a live order. Takes the broker's own order ID (Order.brokerOrderId),
   * NOT our internal IdempotencyKey.
   * Returns the post-modify Order snapshot — the caller does not need a
   * second getOrder call to see the updated state.
   */
  modifyOrder(
    creds: BrokerCredentials,
    brokerOrderId: BrokerOrderId,
    patch: OrderPatch
  ): Promise<ModifyResult>;

  /**
   * Cancel an order. Takes the broker's own order ID (Order.brokerOrderId).
   * Returns the post-cancel Order snapshot. Inspect order.filledQuantity and
   * order.status to determine how much was filled before the cancel took effect.
   * The order may have status PARTIAL if some fills executed before the cancel.
   */
  cancelOrder(
    creds: BrokerCredentials,
    brokerOrderId: BrokerOrderId
  ): Promise<ModifyResult>;

  /**
   * Fetch the current state of an order. Takes the broker's own order ID
   * (Order.brokerOrderId), NOT our internal IdempotencyKey.
   *
   * MUST return the complete fill history to date. If the broker requires a
   * separate API call to retrieve individual fills (e.g. Zerodha's
   * /orders/{id}/trades endpoint), the adapter MUST make that call and merge
   * the results. Returning fills: [] when fills have occurred is a contract
   * violation.
   */
  getOrder(
    creds: BrokerCredentials,
    brokerOrderId: BrokerOrderId
  ): Promise<Order>;

  listOrders(creds: BrokerCredentials): Promise<Order[]>;

  /**
   * Subscribe to real-time fill events for this session.
   * Always returns an Unsubscribe function — call it to tear down the
   * WebSocket / SSE connection. If supportsStreamingFills is false, returns
   * a no-op function immediately; the caller's cleanup code is identical either
   * way.
   *
   * onFill receives individual fill events. Fill.fillQuantity is the quantity
   * for THIS event only (not cumulative). Accumulate across events to reproduce
   * Order.filledQuantity. Use Fill.tradeId to deduplicate on reconnect — the
   * broker may re-deliver fills already seen.
   */
  subscribeFills(
    creds: BrokerCredentials,
    onFill: (fill: Fill) => void
  ): Unsubscribe;
}
