-- Order idempotency table
-- Referenced by: frontend/lib/brokers/adapter.ts (IdempotencyKey type, placeOrder JSDoc)
-- Purpose: deduplicates broker order submissions across concurrent requests and
--          server restarts. The adapter does INSERT ... ON CONFLICT (user_id,
--          idempotency_key) DO NOTHING before calling the broker. If the INSERT
--          is a no-op (key already exists), it reads the cached result and
--          returns fromCache: true without placing a second order.

CREATE TABLE IF NOT EXISTS public.order_idempotency (
  id                uuid        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id           uuid        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  -- UUID v4, max 36 chars; generated by the caller before placeOrder.
  -- Scoped per user — two different users may coincidentally generate the
  -- same UUID but their rows will not conflict.
  idempotency_key   varchar(36) NOT NULL,
  -- Which broker processed this order.
  broker_id         text        NOT NULL CHECK (broker_id IN ('zerodha', 'upstox', 'dhan')),
  -- Broker's own order identifier, populated after a successful placement.
  -- NULL while the order is in-flight (adapter inserted the row but has not
  -- yet received a response from the broker).
  broker_order_id   text,
  -- Serialised OrderResult (JSON). NULL while in-flight; set once the broker
  -- responds (success or exchange-level rejection both produce a result).
  -- If the adapter crashed after INSERT but before UPDATE, result stays NULL.
  -- Callers that receive fromCache: true with result IS NULL should treat
  -- this as UNKNOWN and call listOrders to reconcile.
  result            jsonb,
  created_at        timestamptz NOT NULL DEFAULT now()
);

-- The conflict target for INSERT ... ON CONFLICT DO NOTHING.
-- Composite on (user_id, idempotency_key) so the unique scope is per-user.
ALTER TABLE public.order_idempotency
  ADD CONSTRAINT order_idempotency_user_key_unique
  UNIQUE (user_id, idempotency_key);

-- Used by cleanup queries that prune rows older than a retention window.
-- Example: DELETE FROM order_idempotency WHERE user_id = $1 AND created_at < now() - interval '30 days'
CREATE INDEX IF NOT EXISTS idx_order_idempotency_user_created_at
  ON public.order_idempotency (user_id, created_at);

-- ─── RLS ─────────────────────────────────────────────────────────────────────

ALTER TABLE public.order_idempotency ENABLE ROW LEVEL SECURITY;

-- Users can read their own rows (needed so the adapter can fetch cached results).
CREATE POLICY "Users can read own idempotency rows"
  ON public.order_idempotency
  FOR SELECT
  USING (auth.uid() = user_id);

-- Users can insert their own rows (the adapter inserts before calling the broker).
CREATE POLICY "Users can insert own idempotency rows"
  ON public.order_idempotency
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can update their own rows (the adapter updates result after broker response).
CREATE POLICY "Users can update own idempotency rows"
  ON public.order_idempotency
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- No DELETE policy — rows are pruned by a server-side cleanup job only,
-- never by the client. This prevents a user from deleting their idempotency
-- record and then re-submitting the same key as a fresh order.
